package com.mercury.sqkon.compiler

import kotlinx.serialization.Serializable

@Serializable
data class User(
    val id: Int,
    val name: String,
//    @SerialName("user_email") val email: String
)
//{
//    companion object {
//        // This would be generated by the plugin
//        val propertyIndices: Map<String, Int> = mapOf(
//            "id" to 0,
//            "name" to 1,
//            "email" to 2
//        )
//    }
//}
