source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "just-the-docs", "~> 0.12"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-redirect-from", "~> 0.16"
end

# Windows + JRuby compatibility
gem "tzinfo", ">= 1", "< 3"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "wdm", "~> 0.1.1", platforms: %i[mingw mswin x64_mingw]

group :development do
  gem "html-proofer", "~> 5.0"
end
